LibreSpark/LibreTV

js/app.js
js/config.js
player.html

在config.js中添加了自定义播放器URL，并在PLAYER_CONFIG中启用广告过滤功能。修改app.js中的playVideo函数，使用自定义播放器替代hoplayer。新增player.html文件，实现自定义播放器功能，支持HLS视频流播放，并集成广告过滤逻辑。

feat(播放器): 添加自定义播放器并启用广告过滤功能

---

readme.md

docs: add Docker deployment instructions and GitHub Actions setup

---

js/api.js

fix: 解决旧版本Safari正则表达式兼容问题

---

js/config.js

Remove proxy URL configuration temporarily

---

css/styles.css
index.html
js/api.js
js/app.js
js/config.js

重构应用程序接口处理，增强对自定义应用程序接口的支持
- 在 API 请求处理中移除对多个自定义 API 的支持。
- 简化了 API 源验证逻辑。
- 引入了一个新函数，用于处理来自自定义 API 的特殊详细信息。
- 更新了应用程序，以便使用复选框管理选定的 API，允许多个选择。
- 增强了搜索功能，以支持多个选定的 API，并改进了对成人内容的过滤。
- 增加了管理自定义 API 的功能，包括添加、编辑和从列表中删除。
- 改进了 UI 元素，使用户在管理 API 源时获得更好的体验。
- 更新了配置，在自定义 API 中加入了用于标记成人内容的属性。

重构应用程序接口处理，增强对自定义应用程序接口的支持

---

player.html

- 手机端点击全屏播放时自动触发横屏
- 即使开启了方向锁定也能横屏

手机端点击全屏播放时自动触发横屏

---

api/proxy/[...path].mjs
functions/proxy/[[path]].js
js/config.js
netlify.toml
netlify/functions/proxy.mjs
package-lock.json
package.json
vercel.json

本项目包含前端静态文件和一个 Serverless Function 代理。部署到不同平台需要注意函数路径和环境变量配置。
1.  **Fork/克隆仓库**: 将本仓库 Fork 或克隆到你的 GitHub/GitLab 账户。
2.  **连接仓库**: 登录 Cloudflare Dashboard -> Pages -> 创建项目 -> 连接你的仓库。
3.  **构建设置**:
*   构建命令：留空 (无需构建)
*   输出目录：留空 (或填 `/`)
4.  **环境变量**: **【关键步骤】** 进入项目设置 -> 函数 -> 环境变量绑定 -> **添加生产和预览环境**的变量：
*   `CACHE_TTL`: `86400` (代理缓存时间，秒)
*   `MAX_RECURSION`: `5` (M3U8 最大递归层数)
*   `USER_AGENTS_JSON`: `["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Safari/605.1.15"]` (JSON 字符串数组格式，至少包含一个 User-Agent)
*   `DEBUG`: `false` (设为 `true` 可在函数日志中看到更多信息)
5.  **部署**: 保存并部署。Cloudflare 会自动识别 `/functions` 目录下的函数。
6.  **[可选]绑定KV空间**: …

通过functions函数为cf pages、vercel、netlify增加使用内置代理

---

js/password.js

https://github.com/LibreSpark/LibreTV/issues/146 修复

fix feat: enhance password protection check to validate SHA-256 hash length feat: enhance password protection check to validate SHA-256 hash length

---

index.html
js/password.js
readme.md

[引入js-sha256库以支持HTTP环境下的SHA-256哈希计算，并增强密码验证功能的兼容性](https://github.com/LibreSpark/LibreTV/commit/bd8fb7f101a1cbce1aa982386de431a35a161d56)

引入js-sha256库以支持HTTP环境下的SHA-256哈希计算，并增强密码验证功能的兼容性

---

css/styles.css
index.html
js/app.js

[优化卡片布局和标题显示，提升用户体验](https://github.com/LibreSpark/LibreTV/commit/08e4dea7a874891a79eec3e4f8d2d58c781d6c00)

优化卡片布局和标题显示，提升用户体验

---

js/douban.js
player.html

- 调整了加载中状态的布局，使用 flex 布局使内容居中显示
- 移除了多余的 mr-2 类，增加了 ml-4 类以调整加载文本的位置
优化前：
优化后：

style(douban): 优化加载中状态的样式

---

about.html
index.html
js/app.js
js/douban.js
js/ui.js
manifest.json
player.html
privacy.html
service-worker.js
watch.html

feat: add PWA support

---

index.html
js/app.js
js/douban.js
js/ui.js

添加配置文件导入导出功能
调整部分元素的层次，解决移动端关闭按钮被遮挡的问题

添加配置文件导入导出功能

---

js/api.js
js/app.js
js/config.js

[新增电影天堂资源API配置](https://github.com/LibreSpark/LibreTV/commit/56189623e77156454daa174f4eeb5c59b3a2fd03)
删除累赘函数

新增电影天堂资源API，删除累赘函数

---

.github/workflows/sync.yml
js/douban.js

[豆瓣热门标签添加边框颜色](https://github.com/LibreSpark/LibreTV/commit/ea83d7ecbd53159a0a1b93945e3116cd4c9ecd85)

豆瓣热门标签添加边框颜色

---

js/douban.js

本次更新包含以下改进与修复：
* **阻止豆瓣卡片链接点击事件冒泡**
修复了点击豆瓣卡片中的链接会触发父级点击事件的问题，避免了潜在的跳转或其他误操作。
* **优化加载动画的渲染方式**
将加载动画从通过 `createElement` 动态创建 DOM 元素，重构为直接插入 HTML 字符串，简化了代码结构，提高了可读性和维护性。
* **优化移动端搜索体验**
* 将 `fillAndSearchWithDouban` 函数改为 `async`，使用 `await` 确保异步搜索流程完整执行；
* 在搜索完成后，若检测为移动端（屏幕宽度 ≤ 768px），自动平滑滚动至页面顶部，提升用户体验。

feat: 优化豆瓣卡片交互及加载体验，提升移动端搜索流程

---

js/wakelock.js
player.html

fix: add wakelock to avoid doze

---

js/app.js
player.html

去掉按钮标题，解决移动端换行问题
修正播放页找不到showToast函数的问题

优化复制链接按钮的样式

---

.github/workflows/version.yml
js/version-check.js

Signed-off-by: JohnsonRan <me@ihtw.moe>

fix: dont't bump version on other repos

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/workflows/docker-build.yml
.github/workflows/sync.yml

ci: simplify workflow & add issue template

---

css/styles.css
index.html
js/app.js

fix: close history or settings panel when click elsewhere

---

js/app.js
js/ui.js

feat: import from URL

---

js/ui.js
player.html

修复从历史播放未能恢复时间轴
~~上个PR分支不小心被我删了~~

fix: play from history

---

package-lock.json
package.json

- 在 package.json 中添加 node-fetch 依赖，版本为 ^3.3.2
- 更新 package-lock.json，增加 node-fetch 及其相关依赖的详细版本信息
fix: https://github.com/LibreSpark/LibreTV/pull/457#issuecomment-2888372940

build(deps): 添加 node-fetch 依赖

---

js/app.js
js/player.js
js/ui.js
js/watch.js

fix(player): 同名剧不会被替代 & 实时刷新剧集列表

---

js/player.js
js/ui.js
player.html

fix(player): 调整z-index值并添加全屏状态恢复逻辑

---

js/player.js

这段修改会在鼠标静止2秒后隐藏播放器的工具条按钮。
有点忙没经过太多测试，目前看起来没什么大问题。
https://github.com/LibreSpark/LibreTV/issues/573

自动隐藏播放器的工具栏

---

Dockerfile
docker-compose.yml

docker compose 部署后所有文件默认存在于当前目录
close #251 #201 
Signed-off-by: JohnsonRan <me@ihtw.moe>

feat(compose): show files on host machine

---

js/config.js
js/douban.js

Signed-off-by: JohnsonRan <me@ihtw.moe>

fix: `dbzy.com` ENOTFOUND

---

js/player.js

使用时发现：
1. 播放器在多屏幕设备的某个屏幕全屏时，鼠标从该屏幕移出到其它屏幕后，播放器的控制栏没有自动隐藏，导致播放过程中控制栏一直在播放器下方显示，影响观看体验。
2. 修改过程中发现 artplayer 没有 'fullscreenWeb:enter'、'fullscreenWeb:exit' 事件，因此原来控制播放器控制栏的代码并没有实际起作用，而是 artplayer 默认的实现在起作用，注释掉相关代码进行验证也确认了这一点。
本 PR 针对上面两个问题进行修改。

fix: 播放器在副屏全屏时，鼠标移出副屏后播放器控制栏没有自动隐藏

---

index.html
js/config.js
js/customer_site.js
player.html

增加  js/cusotmer_site.js 可以使项目fork后添加自定义API进入内置API，解决浏览器清除缓存自定义API失效的问题。
修改 js/config.js 将 API_SITES 变量暴漏到全局
修改 index.html 和 player.html 引入 js/cusotmer_site.js

fix: 解决 Issue #110 (新添加的api不会保存)
